#! /bin/bash
export LANG=C.UTF-8
export LC_ALL=C.UTF-8
export FLASK_APP=asx.py
export PYTHONPATH=../stockdb:$PYTHONPATH
[ -f .secret_key ] || python3 -c "import secrets; print(secrets.token_hex(32))" > .secret_key
export SECRET_KEY=$(cat .secret_key)
flask run --host=0.0.0.0
